services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Asia/Kolkata"
      WEBPASSWORD: hello123
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
      - "./adslist.txt:/etc/pihole/adslist.txt"
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 127.0.0.1
    networks:
      router_subnet:
        ipv4_address: 192.168.0.150 # Assign the static IP here

networks:
  router_subnet:
    ipam:
      config:
        - subnet: 192.168.0.0/24
