networks:
  pihole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16 # Define a subnet for your custom network

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: "Asia/Kolkata"
      WEBPASSWORD: hello123
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
      - "./adslist.txt:/etc/pihole/adslist.txt"
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 127.0.0.1
    networks:
      pihole_network:
        ipv4_address: 172.28.0.10
